export const languages = [
    { label: "Português (Portugal, Brasil)", value: "pt" },
    { label: "Inglês", value: "en" },
    { label: "Espanhol", value: "es" },
    { label: "Chinês (simplificado)", value: "zh-CN" },
    { label: "Chinês (tradicional)", value: "zh-TW" },
    { label: "Africâner", value: "af" },
    { label: "Albanês", value: "sq" },
    { label: "Amárico", value: "am" },
    { label: "Árabe", value: "ar" },
    { label: "Armênio", value: "hy" },
    { label: "Assamês", value: "as" },
    { label: "Aymara", value: "ay" },
    { label: "Azerbaijano", value: "az" },
    { label: "Bambara", value: "bm" },
    { label: "Basco", value: "eu" },
    { label: "Bielorrusso", value: "be" },
    { label: "Bengalês", value: "bn" },
    { label: "Boiapuri", value: "bho" },
    { label: "Bósnio", value: "bs" },
    { label: "Búlgaro", value: "bg" },
    { label: "Catalão", value: "ca" },
    { label: "Cebuano", value: "ceb" },
    { label: "Córsico", value: "co" },
    { label: "Croata", value: "hr" },
    { label: "Tcheco", value: "cs" },
    { label: "Coreano", value: "da" },
    { label: "Divehi", value: "dv" },
    { label: "Dogri", value: "doi" },
    { label: "Holandês", value: "nl" },
    { label: "Esperanto", value: "eo" },
    { label: "Estoniano", value: "et" },
    { label: "Ewe", value: "ee" },
    { label: "Filipino (Tagalog)", value: "fil" },
    { label: "Finlandês", value: "fi" },
    { label: "Francês", value: "fr" },
    { label: "Frísio", value: "fy" },
    { label: "Galego", value: "gl" },
    { label: "Georgiano", value: "ka" },
    { label: "Alemão", value: "de" },
    { label: "Grego", value: "el" },
    { label: "Guarani", value: "gn" },
    { label: "Gujarati", value: "gu" },
    { label: "Crioulo haitiano", value: "ht" },
    { label: "Hauçá", value: "ha" },
    { label: "Havaiano", value: "haw" },
    { label: "Hebraico he ou", value: "iw" },
    { label: "Hindi", value: "hi" },
    { label: "Hmong", value: "hmn" },
    { label: "Húngaro", value: "hu" },
    { label: "Islandês", value: "is" },
    { label: "Igbo", value: "ig" },
    { label: "Ilocano", value: "ilo" },
    { label: "Indonésio", value: "id" },
    { label: "Irlandês", value: "ga" },
    { label: "Italian", value: "it" },
    { label: "Japonês", value: "ja" },
    { label: "Javanês", value: "jv" },
    { label: "Canarês", value: "kn" },
    { label: "Cazaque", value: "kk" },
    { label: "Cmer", value: "km" },
    { label: "Quiniaruanda", value: "rw" },
    { label: "Concani", value: "gom" },
    { label: "Coreano", value: "ko" },
    { label: "Krio", value: "kri" },
    { label: "Curdo", value: "ku" },
    { label: "Curdo (Sorani)", value: "ckb" },
    { label: "Quirguiz", value: "ky" },
    { label: "Laosiano", value: "lo" },
    { label: "Latim", value: "la" },
    { label: "Letão", value: "lv" },
    { label: "Lingala", value: "ln" },
    { label: "Lituano", value: "lt" },
    { label: "Luganda", value: "lg" },
    { label: "Luxemburguês", value: "lb" },
    { label: "Macedônio", value: "mk" },
    { label: "Maithili", value: "mai" },
    { label: "Malgaxe", value: "mg" },
    { label: "Malaio", value: "ms" },
    { label: "Malaiala", value: "ml" },
    { label: "Maltês", value: "mt" },
    { label: "Maori", value: "mi" },
    { label: "Marata", value: "mr" },
    { label: "Meiteilon (Manipuri)", value: "mni-Mtei" },
    { label: "Mizo", value: "lus" },
    { label: "Mongol", value: "mn" },
    { label: "Mianmar (birmanês)", value: "my" },
    { label: "Nepalês", value: "ne" },
    { label: "Norueguês", value: "no" },
    { label: "Nianja (Chichewa)", value: "ny" },
    { label: "Oriá", value: "or" },
    { label: "Oromo", value: "om" },
    { label: "Pashto", value: "ps" },
    { label: "Persa", value: "fa" },
    { label: "Polonês", value: "pl" },
    { label: "Punjabi", value: "pa" },
    { label: "Quíchua", value: "qu" },
    { label: "Romeno", value: "ro" },
    { label: "Russo", value: "ru" },
    { label: "Samoano", value: "sm" },
    { label: "Sânscrito", value: "sa" },
    { label: "Escocês gaélico", value: "gd" },
    { label: "Sepedi", value: "nso" },
    { label: "Sérvio", value: "sr" },
    { label: "Sesoto", value: "st" },
    { label: "Xona", value: "sn" },
    { label: "Sindi", value: "sd" },
    { label: "Sinhala (cingalês)", value: "si" },
    { label: "Eslovaco", value: "sk" },
    { label: "Esloveno", value: "sl" },
    { label: "Somali", value: "so" },
    { label: "Sundanês", value: "su" },
    { label: "Suaíli", value: "sw" },
    { label: "Sueco", value: "sv" },
    { label: "Tagalo (filipino)", value: "tl" },
    { label: "Tajique", value: "tg" },
    { label: "Tâmil", value: "ta" },
    { label: "Tártaro", value: "tt" },
    { label: "Telugu", value: "te" },
    { label: "Tailandês", value: "th" },
    { label: "Tigrínia", value: "ti" },
    { label: "Tsonga", value: "ts" },
    { label: "Turco", value: "tr" },
    { label: "Turcomano", value: "tk" },
    { label: "Twi (Akan)", value: "ak" },
    { label: "Ucraniano", value: "uk" },
    { label: "Urdu", value: "ur" },
    { label: "Uyghur", value: "ug" },
    { label: "Usbeque", value: "uz" },
    { label: "Vietnamita", value: "vi" },
    { label: "Galês", value: "cy" },
    { label: "Xosa", value: "xh" },
    { label: "Ídiche", value: "yi" },
    { label: "Iorubá", value: "yo" },
    { label: "Zulu", value: "zu" },
]